# Generated by Django 3.1.2 on 2020-11-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgamer',
            old_name='game',
            new_name='event',
        ),
    ]
